### ISSUE TITLE
Windower Crash on Launch

### ISSUE THREAD

**Issue by Saeyent** [Windower/packages#117]
Windower 5 crashes on startup.

Crash Dump can be found here:
https://drive.google.com/file/d/1URpyFzDEGxDvz68vFiMbaJduDNujJFUT/view?usp=sharing

**Comment by alphaONE2** [comment]
I've just pushed out a fix for this issue. However, since this crash happens in the updater, you will probably need to manually update your windower.exe file. You can get the new version of the file from http://windower.github.io/windower/test/windower.exe
