### ISSUE TITLE
NPC Text / System Text extra whitespace

### ISSUE THREAD

**Issue by Saeyent** [Windower/packages#123]
NPC Text has extra whitespace in it when displaying on screen.  This is most noticeable with Trusts, but can occur on several NPC / System text events, such as during quest dialogue (no screenshot available).

Example below.
![trusttextissue](https://user-images.githubusercontent.com/3395320/43032127-4bc9f5ba-8c64-11e8-8016-aa2b29f1928b.PNG)

Sample (not exactly the same unfortunately) of Windower v4 functionality:
![trusttestv4](https://user-images.githubusercontent.com/3395320/43032157-15ce9730-8c65-11e8-9b2b-733371bd15c9.PNG)

Simplest steps to reproduce (simulates first screenshot):
1) Zone into Ceizak Battlegrounds
2) Summon Apururu
3) Release Apururu 
4) Summon Jaochim
5) Summon Koru-Moru
6) Summon Kupofried
7) Summon KuyinHathdenna

**Comment by z16** [comment]
I assume you're not using any chat modifying addons such as `timestamp`?

**Comment by z16** [comment]
To clarify, NPC output is messy all on its own in FFXI, and it does a bit of cleanup. Some text events fire multiple times, and it can easily result in such an output if chat modification is not careful. The `Timestamp` addon in v4 caused similar issues, which is why it looks much more complicated than it would seem like it needed to be.

**Comment by alphaONE2** [comment]
Can you give us repro steps that don't involve summoning trusts? preferably some NPCs in the base game or an earlier expansion? pre-CoP would be ideal. or do most NPCs have this issue?

**Comment by Saeyent** [comment]
In order of comments:
1) This is Windower 5 without any packages loaded
2) Understood.
3) I will look for options pre-CoP.

**Comment by alphaONE2** [comment]
I can do anything up to Adoulin, but it's much faster and easier if I can repo this on a private test server since I can skip the login process. Which is why I ask for something pre-CoP, but if that's not feasible...

**Comment by Saeyent** [comment]
I will try find a CS that breaks again. I'll backtrack progress over the last 2 weeks and try identify the CS it happened in / replay it somehow.

**Comment by Saeyent** [comment]
![image](https://user-images.githubusercontent.com/3395320/43174013-c0dfd562-8f6c-11e8-8745-62d892e1e6e0.png)
This looks to have solved the issue. Proof of working summoning of NPCs above.

There do appear to be "unrelated" issues though, where a macro like this:
![image](https://user-images.githubusercontent.com/3395320/43174057-089059d6-8f6d-11e8-9f59-28755d995e76.png)

Shows up in the current chat mode:
![image](https://user-images.githubusercontent.com/3395320/43174109-31951060-8f6d-11e8-89f1-38db04c7edc5.png)

**Comment by Saeyent** [comment]
To be clear, I am unsure if your fix for the NPC text is related to the / change, but the DLL you asked me to test had this issue.

**Comment by alphaONE2** [comment]
I'm closing this as fixed. I've opened a new issue for the auto-translate bug

**Comment by Saeyent** [comment]
Thank you, agree, this issue is fixed.
