### ISSUE TITLE
Windower Crash attempting to install equipment

### ISSUE THREAD

**Issue by Saeyent** [Windower/packages#125]
[2018-07-21T18-58-18-4312673Z.zip](https://github.com/Windower/packages/files/2216420/2018-07-21T18-58-18-4312673Z.zip)
Attempting to install equipment, windower crashed.  The equipment files were downloaded.

Running packages at time of crash:
timestamp

Steps taken to cause crash:
Run the following from FFXI:
```
/install equipment
```

**Comment by z16** [comment]
Closing, since everything has changed so much that it may or may not be resolved. Feel free to reopen it if the same issue persists.
