### ISSUE TITLE
v4 compatibility layer

### ISSUE THREAD

**Issue by z16** [Windower/packages#15]
A (preferably simple to install) compatibility layer to v4's API. Full compatibility is impossible, since v4 uses a custom Lua parser. So at least in this case (and possibly more places) some addons/libraries would need to be adjusted.

We also need to check how some coroutine specific features of LuaCore or custom user environments differ on v5.

Has various requirements before it can be implemented (although partial implementation could start at any point):
1. Player
2. Inventory
3. Mob array
4. Packet
5. Resources
6. Text/primitive display
7. v4's libraries all need to run without problems (probably on the same compatibility layer)

Probably more...

**Comment by alphaONE2** [comment]
We've decided not to include a compatibility layer at this time.
