### ISSUE TITLE
Issue while running on Wine (3.16)

### ISSUE THREAD

**Issue by Conmanx360** [Windower/packages#151]
Hi!

I saw on the forums it was mentioned that you guys were interested in getting this working on Linux through Wine. After getting some bugs fixed on the Wine side and getting Windower to run, Windower gives a crash after starting the game. Not sure if it's something that needs to be solved on the Windower side, or the Wine side. Either way, if you could point me to where the issue seems to be, I could see what I can do.

Crash dump from Windower here: https://drive.google.com/open?id=164If2wuK6ngjLjfvz6Uvlvhok54-80vV

Thanks.

**Comment by alphaONE2** [comment]
Fixed by Windower/windower#249
