### ISSUE TITLE
packet_service crashing - packet object is no longer valid

### ISSUE THREAD

**Issue by Saeyent** [Windower/packages#189]
Symptom:
On loading/connecting with a new character, the packet_service crashes.
Trying to manually reload the packet_service after it crashes causes it to crash again.

First few lines replicated, see screenshots for more:
packet_service:packet_service.lua:309: packet object is no longer valid
(upvalue) error
  [native] core.dll!0x562a8190
  locals:
    (*temporary) = [string] packet object is no longer valid
(metamethod) __index
  src\addon\modules\packet.lua:115

Steps followed to attempt fix:
1) Validate packet_service.lua is up to date with github
2) Validate that the core.dll is current
3) used core.dll from Iryoku on discord

Other information:
1) core.dll version: 5.0.6945.30679
2) Windows updates around the time of issue first occurring: KB4480966, KB4483234

screenshots of dev console:
![image](https://user-images.githubusercontent.com/3395320/51153817-6e4ee980-1826-11e9-90b3-d9f28cf3138a.png)
![image](https://user-images.githubusercontent.com/3395320/51153842-845caa00-1826-11e9-9938-de7e9c6b65ff.png)

Reload of packet_service:
![image](https://user-images.githubusercontent.com/3395320/51153752-39429700-1826-11e9-951c-48a9405da1e9.png)
![image](https://user-images.githubusercontent.com/3395320/51153784-524b4800-1826-11e9-8f22-cc7f395cfe49.png)

**Comment by z16** [comment]
Just to clarify, this issue is in the core lib and not anything the external service or lib does. It happens on a new install with no packages and services loaded with an addon that simply says:

```lua
local packet = require('packet')

packet.incoming:register(print)
```

This results in the following output:
```
windower.packet: invalid        1547519864
```

And if you try to access any of the packet object's properties like `p.id` it errors with `packet object is no longer valid`.

**Comment by z16** [comment]
Kinda "fixed". We disabled the check for now, so this won't happen anymore, and we will refactor the mechanism that caused it so it's no longer necessary in the first place.
