### ISSUE TITLE
Command argument string incorrect bracket pairing

### ISSUE THREAD

**Issue by svanheulen** [Windower/packages#251]
If your argument string is for an optional argument you can't have a `]` anywhere in your pattern. Similarly you can't have a `>` in your pattern if it's a required argument. For example, these will all cause errors:
```lua
command.arg.parse("<string(>)>")
command.arg.parse("[string(])]")
command.arg.parse("[string([%+%-]?d%+)]")
```

**Comment by z16** [comment]
This should be fixed. However, to use the opening type of brace in a pattern you will need to escape it with a `\` (or two `\`, if you use it within Lua code). So in a Lua file your examples would look like this:
```lua
command.arg.parse("<string(\\>)>")
command.arg.parse("[string(\\])]")
command.arg.parse("[string([%+%-\\]?d%+)]")
```

(That said I think your last example is meant to be `%d` at the end.)
