### ISSUE TITLE
Equipment extdata does not refresh all data correctly

### ISSUE THREAD

**Issue by Saeyent** [Windower/packages#282]
The following code appears to demonstrate an issue in equipment. Equipment is not properly refreshed after the first time that it is accessed.

Using the sample code below, the extdata can be examined on augmented items.
This works for the first time that the equipment is accessed.
Changing to another job, viewing an item and then changing back is where the issue presents.
The extdata is set to blank as seen in the screenshots below the code.

Sample `bug.lua`
```lua
local chat = require('chat')
local command = require('command')
local equipment = require('equipment')
local util = require('util')

local show_equipped = function(slot)    
    if slot >= 0 and slot < 16 then
        local item = equipment[slot]
        if type(item) == 'table' or type(item) == 'cdata' then
            item = util.vstring(item)
        end
        chat.add_text('Slot '.. slot .. ' : ' .. (item or '-'))
    end
end

local bug_command = command.new('bug')

bug_command:register('show', show_equipped, '<slot:number>')
```
Example of output (broken: note that extdata has only 00 for data):
![image](https://user-images.githubusercontent.com/3395320/60538719-fedb9200-9cbf-11e9-953c-e294ee9b832a.png)

Example of in game item (demonstrates that it is augmented):
![image](https://user-images.githubusercontent.com/3395320/60538827-32b6b780-9cc0-11e9-9a12-931aa5a4f0b7.png)
Example of what extdata should be:
![image](https://user-images.githubusercontent.com/3395320/60539156-e3bd5200-9cc0-11e9-9dff-e5c2110a0229.png)

Attempts to fix:
Restart game: does not persist the extdata after 2 job changes
`/reloadall` does not fix extdata once broken

**Comment by Saeyent** [comment]
This issue is user error (mine).

Corrected code should be (thanks to Nifim):
```lua
local chat = require('chat')
local command = require('command')
local equipment = require('equipment')
local util = require('util')

local show_equipped = function(slot)    
    if slot >= 0 and slot < 16 then
        local item_name = util.vstring(equipment[slot])        
        chat.add_text('Slot '.. slot .. ' : ' .. (item_name or '-'))
    end
end

local bug_command = command.new('bug')

bug_command:register('show', show_equipped, '<slot:number>')
```

**Comment by Saeyent** [comment]
Re-opening.  The "working" code above breaks when doing the following:

1) Log in
2) Zone out
3) get new weapon from magian moogle
4) equip weapon

When using the above code subsequent to that, the equipment[1] slot still holds the data of the previous weapon.

Changing equipment does not resolve the array.

**Comment by Saeyent** [comment]
Additional attempts to resolve:
1. Zoning did not fix the issue
2. changing jobs in mog house did fix the issue

**Comment by Saeyent** [comment]
If I change weapons 3 times, the 2nd weapon now shows in the array.

**Comment by RubenatorX** [comment]
Did some testing... its not always the 2nd most recent piece... its.. kind of random honestly.
Using this code:
```lua
local chat = require('chat')
local command = require('command')
local equipment = require('equipment')

local bug_command = command.new('bug')

local heads = {
    [1] = "Ebers Cap +1",
    [2] = "Telchine Cap",
    [3] = "Vanya Hood",
    [4] = "Ebers Cap +1",
    [5] = "Vanya Hood",
    [6] = "Sol Cap",
    [7] = "Ebers Cap +1",
    [8] = "Telchine Cap",
    [9] = "Ebers Cap +1",
    [10] = "Vanya Hood",
    [11] = "Telchine Cap",
    [12] = "Ebers Cap +1",
    [13] = "Telchine Cap",
    [14] = "Vanya Hood",
    [15] = "Ebers Cap +1",
    [16] = "Vanya Hood",
    [17] = "Ebers Cap +1",
    [18] = "Sol Cap",
}
bug_command:register(function() 
    chat.add_text("starting... " .. "equipment[4].item.item.name: "..equipment[4].item.item.name)
    coroutine.sleep(2)
    for i, item_name in pairs(heads) do
        command.input('/equip head "'..item_name..'"')
        coroutine.sleep(4)
        chat.add_text('/equip head "'..item_name..'"'..' => equipment[4].item.item.name: '..equipment[4].item.item.name)
        coroutine.sleep(2)
    end
    chat.add_text("test completed")
end)
```

Produced these sorts of results:
![image](https://user-images.githubusercontent.com/5944121/60627194-8e5d6f80-9daa-11e9-8e2c-4cb7bb944252.png)

**Comment by Saeyent** [comment]
Retested using @RubenatorX's script, 

Altered for items, as well as doing 3 different time delays
Image below is for 2 second delays, 1 second delays, and 0 second delays between the equip and accessing the inventory to display it.

2 second delay - equipment in memory updated as expected
1 second delay - equipment in memory updated as expected
0 second delay -  equipment in memory did not update which is expected

![image](https://user-images.githubusercontent.com/3395320/60682531-76d4c400-9e48-11e9-9c16-47abcb031fde.png)
