### ISSUE TITLE
UI: Button text alignment

### ISSUE THREAD

**Issue by Nifim** [Windower/packages#332]
Button text alignment is not centered when a button has a custom size.

Button with Custom Size
![image](https://user-images.githubusercontent.com/4059879/68344434-d87d9700-00a3-11ea-82d8-cb6a28c9474f.png)
Button with automatic Size
![image](https://user-images.githubusercontent.com/4059879/68344469-ee8b5780-00a3-11ea-8d63-2ee9bde25986.png)

**Comment by alphaONE2** [comment]
This should be fixed with the recent UI rewrite.
