### ISSUE TITLE
action_service crashes on action packet

### ISSUE THREAD

**Issue by gdiShun** [Windower/packages#333]
The action_service will crash immediately on the first action packet it receives with this error:

> [core] action_service loaded
> [action_service] packets:packets.lua:285: Invalid packet path: /block
> [action_service] (global)<unknown>
> [action_service]   [native]core.dll!0x5d54f050
> [action_service]   locals:
> [action_service]     (*temporary) = [string]Invalid packet path: /block
> [action_service] (metamethod)<unknown>
> [action_service]   packets:packets.lua:285
> [action_service]   locals:
> [action_service]     t = [table]table: 0x0cdccc28
> [action_service]     k = [string]block
> [action_service]     path = [string]/block
> [action_service]   upvalues:
> [action_service]     path_cache = [table]table: 0x0cdc74c8
> [action_service]     tostring = [function]function: builtin#19
> [action_service]     make_table = [function]function: 0x0cdcd690
> [action_service]     setmetatable = [function]function: builtin#9
> [action_service]     final_meta = [function]function: 0x0cdd1298
> [action_service]     packet_meta = [table]table: 0x0cdd12b8
> [action_service] (upvalue)<unknown>
> [action_service]   action_service:action_service.lua:57
> [action_service]   locals:
> [action_service]     p = [cdata]cdata<struct 198 &>: 0x0e1e06c8
> [action_service]     info = [cdata]cdata<struct 158 &>: 0x0e1e06c8
> [action_service]     packet = [cdata]cdata<struct 198 &>: 0x0e1e06c8
> [action_service]     (*temporary) = [table]table: 0x0cdccc28
> [action_service]     (*temporary) = [table]table: 0x0cdccc28
> [action_service]     (*temporary) = [cdata]ctype<struct 158 *>
> [action_service]     (*temporary) = [number]9.4556493054057e-247
> [action_service]   upvalues:
> [action_service]     cat_out = [cdata]cdata<struct outgoing_category_constants>: 0x0cdb2538
> [action_service]     packets = [table]table: 0x0cdccc28
> [action_service]     blocked = [boolean]false
> [action_service]     filter_action_event = [table]windower.event:222016064
> [action_service]     pre_action_event = [table]windower.event:222016016
> [action_service]     mid_action_event = [table]windower.event:222015968
> [action_service]
> [action_service]   packets:packets.lua:83
> [action_service]   upvalues:
> [action_service]     fn = [function]function: 0x0cdccee8
> [action_service]     get_packet = [function]function: 0x0cdcc2b8
> [action_service]     current_address = [number]236848840
> [action_service]     current = [cdata]cdata<struct 158 &>: 0x0e1e06c8
> [action_service]
> [action_service]   [string]core.event
> [action_service]   locals:
> [action_service]     (*temporary) = [string]windower.event:219963112
> [action_service]     (*temporary) = [table]table: 0x0cdbbb98
> [action_service]     (*temporary) = [function]function: builtin#4
> [action_service]     (*temporary) = [table]table: 0x0cdc4c30
> [action_service]     (*temporary) = [number]nan
> [action_service]     (*temporary) = [function]function: 0x0cdc7c38
> [action_service]     (*temporary) = [boolean]true
> [action_service]     (*vararg) = [string]LJ    K 
> [action_service]   upvalues:
> [action_service]      = [table]table: 0x0cdae9c8
> [core] action_service unloaded

It's 100% reproduce-able for me by simply logging in or /load action_service'ing, then receiving an action packet. Whether my own or someone else's action.

**Comment by Nekseus** [comment]
Yes this is a known error. Its currently being worked on. It has to do with the specific packet used in `action_service`.

**Comment by z16** [comment]
Just for the record, the underlying bug is in the action packet itself, the service just happens to rely on it very much, but anything else using that packet is equally broken. The error has been identified but required a large-scale refactoring, which is on the verge of completion.

**Comment by z16** [comment]
Took longer than expected, but has also been fixed for a while now.
