### ISSUE TITLE
seriously when is the root of this getting fixed im sick of using windower 4

### ISSUE THREAD

**Issue by Nekseus** [Windower/packages#336]
https://github.com/Windower/packages/blob/20841975e77e59ab50d4224d223721cc7f55c6df/packet_service/types.lua#L617

**Comment by Nekseus** [comment]
its been over 6 months

**Comment by RubenatorX** [comment]
No one is stopping you from fixing it

**Comment by Nekseus** [comment]
its a source problem. i dont have source access no more. 😄

**Comment by Nekseus** [comment]
arcon kicked me out for having opinions and talking back to ashita users slandering windower so yeah i dont have access ot the source repo no more. lol

**Comment by Nekseus** [comment]
I know your an expert so i figured id fill you in on the facts 😉

**Comment by z16** [comment]
Can't say when it will be fixed. Closing as it's a duplicate of #333.
