### ISSUE TITLE
Is there a way to get this to stop changing my preferences? Config file

### ISSUE THREAD

**Issue by Mercurian** [Windower/packages#337]
This damn file constantly rewrites itself for the frame divisor, which is fine... but when it does sometimes it changes my lock-on feature. Kind of getting sick of it.

I manually set it to false. I save it, I reload it. hours later the god damn thing is back on true again. How do I make that stop!

**Comment by RubenatorX** [comment]
One possible way for this to happen, is if you are introducing a syntax error into the settings file when you edit it, then on reload it will wipe it out and make default settings again. Dunno if that's what's happening to you but, just tossing that out there.

**Comment by Nifim** [comment]
Just to confirm you are asking about the config addon for the alpha version of windower v5 right? not v4

**Comment by Mercurian** [comment]
Windower 4

and no there's no error, the file just edits itself a couple times a day for no apparent reason

**Comment by z16** [comment]
Are you using FastCS? Either way, this tracker is solely for Windower 5 addons, please open a new issue [here](https://github.com/Windower/Lua/issues).
