### ISSUE TITLE
Zone messages resource

### ISSUE THREAD

**Issue by Byrth** [Windower/packages#57]
Zone messages aren't parsed out of resources and distributed because there are too many and they are too big, but it would be really useful to have for an addon like `pointwatch` that rely on zone message IDs.

SE occasionally inserts messages and thus changes the absolute address of messages, but rarely inserts a message inside a relevant cluster of messages, so the address of a message relative to another similar message rarely changes.

So `fishing message A`'s address +5 is a reliable location for `fishing message E`, but 8530 is an unreliable location for `fishing message A`. If we had a resource like this, you could parse the current zone message .dat and iterate over the resources to find `fishing message A` on zone (thus getting reliable addresses for fishing messages A~Z).

**Comment by z16** [comment]
Done, see `client_data.strings`.
