### ISSUE TITLE
Game sound not working with v5

### ISSUE THREAD

**Issue by Iminiillusions** [Windower/packages#65]
Game sound doesn't play at all, despite any sound settings I mess with when running the game with v5. Sound plays just fine with Vanilla Launcher and v4.

**Comment by alphaONE2** [comment]
I can't replicate this. Can anyone else?

**Comment by cairface** [comment]
I cannot.

**Comment by Nifim** [comment]
thought it might be not having config doing it, but i cant manage to replicate it either.

**Comment by zetaepyon** [comment]
Unable to replicate here too.

**Comment by alphaONE2** [comment]
Closing this issue, since we can't replicate it
